language: python

python:
    - "3.5"

env: 
    - TOX_ENV=py35-django-110
    - TOX_ENV=py34-django-110
    - TOX_ENV=py27-django-110

matrix:
    fast_finish: true

install:
    - pip install -r requirement-test.txt

script:
    - tox -e $TOX_ENV

after_success:
    - codecov -e TOX_ENV
