language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env: 
  - TOX_ENV=py36-django-110
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110

matrix:
  fast_finish: true

install:
  - pip install -r requirement-test.txt

script:
  - tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
