# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_custom_user', '0002_auto_20170705_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 14, 16, 33, 486290, tzinfo=utc)),
        ),
    ]
